<template>
  <div>
    <div id="Realisations">
      <img
        class="container-tableauImg__img fade-in"
        src="../assets/tableau.webp"
        alt=""
      />
    </div>
    <div
      class="your mx-auto container"
      style="background-color: rgba(0, 0, 0, 0.5)"
    >
      <div class="your-headText" style="padding: 8rem 0 8rem 0">
        <h1 class="your-header text-white">Tableaux de Kareshma</h1>
        <p class="your-para text-white fs-5">
          J'ai toujours été passionné par la peinture, l'art et l'imagination.
          Transposer des éléments cachés et enfouis tout au fond de notre esprit
          sur une feuille blanche est tout de même un défis. Retrouvez
          ci-dessous mes inspirations et vos inspirations.
        </p>
        <div
          class="container container-fontfamily d-flex flex-wrap justify-content-center"
          style="margin-top: 5rem"
        >
          <a
            class="button col-md-4 text-decoration-none mx-auto"
            href="#MyInspiration"
          >
            <div class="cards d-flex mx-auto rounded">
              <div>
                <h2 class="text-white cards-inspiration">Mes inspirations</h2>
              </div>
            </div>
          </a>
          <a
            class="button col-md-4 text-decoration-none mx-auto"
            href="#YourInspiration"
          >
            <div class="cards d-flex mx-auto rounded">
              <div>
                <h2 class="text-white cards-inspiration">Vos inspirations</h2>
              </div>
            </div>
          </a>
        </div>
      </div>
      <div id="scroll_to_top">
        <a href="#Realisations"
          ><i
            class="fa-solid fa-circle-arrow-up"
            style="font-size: 5rem; color: yellow"
          ></i
        ></a>
      </div>
    </div>
    <my-inspiration id="MyInspiration"></my-inspiration>
    <your-inspiration id="YourInspiration"></your-inspiration>
  </div>
</template>

<script>
import YourInspiration from "./YourInspiration.vue";
import MyInspiration from "./MyInspiration.vue";

export default {
  components: {
    YourInspiration,
    MyInspiration,
  },
};
</script>

<style>
.container-tableauImg__img {
  object-fit: contain;
  width: 100%;
}

.realisations {
  font-family: new-order, sans-serif;
  font-weight: 200;
  font-style: normal;
  background-color: #ff8a00;
}

.button {
  display: inline-block;
  padding: 15px 25px;
  font-size: 24px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  border: none;
  border-radius: 15px;
  box-shadow: 0 9px #999;
}
.button:hover {
  background-color: #3e8e41;
}

.button:active {
  background-color: #3e8e41;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}
.heading {
  font-size: 20px;
  font-weight: 600;
  color: #3d5afe;
}

.line1 {
  color: #000;
  font-size: 12px;
}

.line2 {
  color: #000;
  font-size: 12px;
}

.line3 {
  color: #000;
  font-size: 12px;
}

.cards {
  width: 120px;
  background-color: transparent !important;
}

.cards-inspiration {
  font-size: 20px;
}

/* CSS */
.button-52 {
  font-size: 16px;
  font-weight: 200;
  letter-spacing: 1px;
  padding: 13px 20px 13px;
  outline: 0;
  border: 1px solid black;
  cursor: pointer;
  position: relative;
  background-color: rgba(0, 0, 0, 0);
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
}

.button-52:after {
  content: "";
  background-color: #ffe54c;
  width: 100%;
  z-index: -1;
  position: absolute;
  height: 100%;
  top: 7px;
  left: 7px;
  transition: 0.2s;
}

.button-52:hover:after {
  top: 0px;
  left: 0px;
}

@media (min-width: 768px) {
  .button-52 {
    padding: 13px 50px 13px;
  }
}

.cards:hover {
  box-shadow: none;
  transform: none;
}
#scroll_to_top {
  z-index: 5;
  position: fixed;
  width: 25px;
  height: 25px;
  bottom: 60px;
  right: 60px;
}
#scroll_to_top img {
  width: 25px;
}
/* Apparition des images*/
.fade-in {
  -webkit-animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 1.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-3-29 17:22:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>
